force-app/main/default/objects/Course__c/fields/Enrolled_Students__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Students__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolled Students</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/classPortal.cls
public with sharing class classPortal {
    @AuraEnabled(cacheable=true)
    public static List<Course__c> showCourses(Id student)
    {
        
      List<Course__c> studentCourses = [SELECT Name FROM Course__c WHERE Enrolled_Students__c =: student];
    return studentCourses;
        // System.debug(student.Name);
        // System.debug('Students Courses ' + studentCourses);
        
    }
}